### PR TITLE
add r61

### LINKED ISSUE #12: [Make-Rule] Perform regular updates
Make : questions.yml + playbook.yml
From : ANSSI
Rule : 61
Level : Minimal

### PR DESCRIPTION
**Pull request by aiglematth**

### CODE REVIEW

**Review by Mijux — CHANGES_REQUESTED** [review]
Wrong title in the playbook.yml, recheck all string before margin

**Comment by aiglematth** [comment]
changed

**Review by Mijux — APPROVED** [review]
perfect !

**Review by 0nid1 — APPROVED** [review]
Great ideas!

**Pull request merged**
